
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Raja
 */
public class PROPERTY_IMAGES_SLIDER extends javax.swing.JFrame {

    /**
     * Creates new form PROPERTY_IMAGES_SLIDER
     */
    
  static int propertyId;
    
    //image list
    
    ArrayList<byte[]> imageList;
    
    // the image index 
    int index;
    
    public PROPERTY_IMAGES_SLIDER( int pid) {
        
        initComponents();
        
        setTitle("Property Image Slider");
        
        this.propertyId = pid;

        // set border  to the jlabel image
        Border jlabel_image_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0, 0, 0));
        jLabel_Image.setBorder(jlabel_image_border);

        // set border  to the next and previus jlabel image
        Border jlabel_prev_border = BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(255, 69, 0));
        jLabel_prevoius.setBorder(jlabel_prev_border);
        jLabel_next.setBorder(jlabel_prev_border);

        // get the image using the hashmap 
        // Convert the Set<byte[]> returned by keySet() to an ArrayList<byte[]>
        HashMap<byte[], Integer> map = new P_PROPERTY().propertiesImageList(propertyId);
        imageList = new ArrayList<>(map.keySet());//for editing code something
        displayImage(index);
   
    }
    
    // create a function to display the image by index 
    public void displayImage( int imageIndex){
        
        Image img= new ImageIcon(imageList.get(imageIndex)).getImage().getScaledInstance(jLabel_Image.getWidth(), jLabel_Image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(img);
        jLabel_Image.setIcon(image);
   
    }
    
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Image = new javax.swing.JLabel();
        jLabel_prevoius = new javax.swing.JLabel();
        jLabel_next = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Image.setOpaque(true);

        jLabel_prevoius.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_prevoius.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel_prevoius.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_prevoius.setText("<");
        jLabel_prevoius.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_prevoius.setOpaque(true);
        jLabel_prevoius.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_prevoiusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_prevoiusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_prevoiusMouseExited(evt);
            }
        });

        jLabel_next.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_next.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel_next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_next.setText(">");
        jLabel_next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_next.setOpaque(true);
        jLabel_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_prevoius, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_next, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_prevoius, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_next, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseClicked
        
        
        index++;
        if(index >= imageList.size()) index = imageList.size() - 1;
        
        displayImage(index);
        
        
        
        
    }//GEN-LAST:event_jLabel_nextMouseClicked

    private void jLabel_prevoiusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prevoiusMouseClicked
        
        // show the previous image 
        index--;
        if(index < 0 ) index = 0;
        displayImage(index);
        
    }//GEN-LAST:event_jLabel_prevoiusMouseClicked

    private void jLabel_nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseEntered
       
        jLabel_next.setBackground(new Color(255,69,0));
        jLabel_next.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_jLabel_nextMouseEntered

    private void jLabel_nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseExited
   
        jLabel_next.setBackground(Color.white);
        jLabel_next.setForeground(Color.black);
        
    }//GEN-LAST:event_jLabel_nextMouseExited

    private void jLabel_prevoiusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prevoiusMouseEntered
        
        jLabel_prevoius.setBackground(Color.orange);
        jLabel_prevoius.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_jLabel_prevoiusMouseEntered

    private void jLabel_prevoiusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_prevoiusMouseExited
        
        jLabel_prevoius.setBackground(Color.white);
        jLabel_prevoius.setForeground(Color.black);
        
    }//GEN-LAST:event_jLabel_prevoiusMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROPERTY_IMAGES_SLIDER(propertyId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_next;
    private javax.swing.JLabel jLabel_prevoius;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
