
import java.awt.Color;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Raja
 */
public class PROPERTY_TYPE_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form PROPERTY_TYPE_WINDOW
     */
    public PROPERTY_TYPE_WINDOW() {
        initComponents();
        // 152,153,153
        Border panel_tittle_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(125, 125, 125));
        jPanel_Tittle.setBorder(panel_tittle_border);
        setTitle("Property Type Window");

        // populate the lsit
        fillTypeList();

    }

    // createa function to populate the jList using the type Hashmap
    public void fillTypeList() {

        P_TYPE type = new P_TYPE();

        HashMap<String, Integer> map = type.getTypeMap();

        DefaultListModel listModel = new DefaultListModel();

        int i = 0;

        for (String typeName : map.keySet()) {

            listModel.add(i, typeName);
            i++;
        }
        jList1.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Tittle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jButton_remove_type = new javax.swing.JButton();
        jButton_add_type = new javax.swing.JButton();
        jButton_edit_type = new javax.swing.JButton();
        jButton_refresh_type = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_Tittle.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Property Type");

        javax.swing.GroupLayout jPanel_TittleLayout = new javax.swing.GroupLayout(jPanel_Tittle);
        jPanel_Tittle.setLayout(jPanel_TittleLayout);
        jPanel_TittleLayout.setHorizontalGroup(
            jPanel_TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TittleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
        );
        jPanel_TittleLayout.setVerticalGroup(
            jPanel_TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TittleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Description:");

        jTextField_name.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });

        jTextArea_description.setColumns(20);
        jTextArea_description.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jTextArea_description.setRows(5);
        jScrollPane1.setViewportView(jTextArea_description);

        jButton_remove_type.setBackground(new java.awt.Color(255, 0, 255));
        jButton_remove_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_remove_type.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove_type.setText("Remove");
        jButton_remove_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_remove_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_remove_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_remove_typeActionPerformed(evt);
            }
        });

        jButton_add_type.setBackground(new java.awt.Color(0, 204, 0));
        jButton_add_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_add_type.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_type.setText("Add");
        jButton_add_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_add_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_typeActionPerformed(evt);
            }
        });

        jButton_edit_type.setBackground(new java.awt.Color(51, 51, 255));
        jButton_edit_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_edit_type.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_type.setText("Edit");
        jButton_edit_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_edit_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_edit_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_typeActionPerformed(evt);
            }
        });

        jButton_refresh_type.setBackground(new java.awt.Color(255, 51, 51));
        jButton_refresh_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_refresh_type.setForeground(new java.awt.Color(255, 255, 255));
        jButton_refresh_type.setText("Refresh");
        jButton_refresh_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_refresh_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_refresh_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refresh_typeActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton_add_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField_name)
                            .addComponent(jTextField_id))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_edit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_remove_type, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_refresh_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_remove_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_edit_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_add_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_refresh_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_remove_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_remove_typeActionPerformed

        //edit the selected type;
        try {
            Integer id = Integer.valueOf(jTextField_id.getText());

            P_TYPE type = new P_TYPE(id, "", "");

            if (!jTextField_id.getText().trim().equals("")) {// if the type name is not empty
                // show a confirmation message before deleting the type 
                int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You Want to Delete this Type", "Delete Type", JOptionPane.YES_NO_OPTION);
                if (yes_or_no == JOptionPane.YES_OPTION) {
                    if (type.execTypeQuery("remove", type)) {
                        JOptionPane.showMessageDialog(null, "Type Deleted ", "Delete Type", 1);
                        
                        // clear text field after the delete 
                        jTextField_id.setText("");
                        jTextField_name.setText("");
                        jTextArea_description.setText("");
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Operation Failed", "Delete Type", 2);
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Enter The Type ID", "Empty Name", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "Enter a Valid Type ID", "Invalid ID", 2);
        }


    }//GEN-LAST:event_jButton_remove_typeActionPerformed

    private void jButton_add_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_typeActionPerformed
        // TODO add your handling code here:
        //add a new type;

        String name = jTextField_name.getText();
        String description = jTextArea_description.getText();

        P_TYPE type = new P_TYPE(0, name, description);

        if (!name.trim().equals("")) {// if the type name is not empty

            if (type.execTypeQuery("add", type)) {

                JOptionPane.showMessageDialog(null, "New Type Added", "Add Type", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Operation Failed", "Add Type", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter The Type Name", "Empty Name", 2);
        }

    }//GEN-LAST:event_jButton_add_typeActionPerformed

    private void jButton_edit_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_typeActionPerformed

        try {
            //edit the selected type;
            Integer id = Integer.valueOf(jTextField_id.getText());

            String name = jTextField_name.getText();
            String description = jTextArea_description.getText();

            P_TYPE type = new P_TYPE(id, name, description);

            if (!name.trim().equals("")) {// if the type name is not empty

                if (type.execTypeQuery("edit", type)) {

                    JOptionPane.showMessageDialog(null, "Type Updated ", "Edit Type", 1);
                } else {
                    JOptionPane.showMessageDialog(null, "Operation Failed", "Edit Type", 2);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Enter The Type Name", "Empty Name", 2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "Enter a Valid Type ID", "Invalid ID", 0);
        }

    }//GEN-LAST:event_jButton_edit_typeActionPerformed

    private void jButton_refresh_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refresh_typeActionPerformed
        // TODO add your handling code here:
        
        // refresh the list data 
        fillTypeList();
        
    }//GEN-LAST:event_jButton_refresh_typeActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

        //display the selectedtype form list to the text fields
        // getting the id using the hashmappe
        P_TYPE type = new P_TYPE();
        HashMap<String, Integer> map = type.getTypeMap();
        Integer typeid = map.get(jList1.getSelectedValue());
        type = type.getTypeById(typeid);
        jTextField_id.setText(type.getID().toString());
        jTextField_name.setText(type.getName());
        jTextArea_description.setText(type.getDescription());


    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_TYPE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_TYPE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_TYPE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_TYPE_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROPERTY_TYPE_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_type;
    private javax.swing.JButton jButton_edit_type;
    private javax.swing.JButton jButton_refresh_type;
    private javax.swing.JButton jButton_remove_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Tittle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea_description;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_name;
    // End of variables declaration//GEN-END:variables
}
