
import java.awt.Color;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Raja
 */
public class PROPERTY_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form PROPERTY_WINDOW
     */
    P_TYPE type = new P_TYPE();
    HashMap<String, Integer> map = type.getTypeMap();

    public PROPERTY_WINDOW() {
        initComponents();

        Border panel_tittle_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(26, 138, 32));
        jPanel_Tittle.setBorder(panel_tittle_border);
        setTitle("Property Window");

        //populate the bindcode
        bindCombo();

    }

    // create a function to populate the Jcombobox with type data
    public void bindCombo() {

        for (String s : map.keySet()) {
            jComboBox1_type.addItem(s);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_Tittle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Address = new javax.swing.JTextArea();
        jButton_remove_property = new javax.swing.JButton();
        jButton_add_property = new javax.swing.JButton();
        jButton_edit_property = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Square_feet = new javax.swing.JTextField();
        jTextField_owner_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Price = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1_Search_Property = new javax.swing.JButton();
        jComboBox1_type = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_Bedrooms = new javax.swing.JSpinner();
        jSpinner_Bathrooms = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner_Age = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Dscription = new javax.swing.JTextArea();
        jCheckBox_Balconey = new javax.swing.JCheckBox();
        jCheckBox_pool = new javax.swing.JCheckBox();
        jCheckBox_Backyard = new javax.swing.JCheckBox();
        jCheckBox_Garage = new javax.swing.JCheckBox();
        jButton_remove_property1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(75, 192, 18));

        jPanel_Tittle.setBackground(new java.awt.Color(65, 160, 10));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Property");

        javax.swing.GroupLayout jPanel_TittleLayout = new javax.swing.GroupLayout(jPanel_Tittle);
        jPanel_Tittle.setLayout(jPanel_TittleLayout);
        jPanel_TittleLayout.setHorizontalGroup(
            jPanel_TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TittleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(353, 353, 353))
        );
        jPanel_TittleLayout.setVerticalGroup(
            jPanel_TittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TittleLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("ID: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Type:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Address:");

        jTextField_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jTextArea_Address.setColumns(20);
        jTextArea_Address.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextArea_Address.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Address);

        jButton_remove_property.setBackground(new java.awt.Color(255, 0, 0));
        jButton_remove_property.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_remove_property.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove_property.setText("Remove");
        jButton_remove_property.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_remove_property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_remove_property.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_remove_propertyActionPerformed(evt);
            }
        });

        jButton_add_property.setBackground(new java.awt.Color(0, 204, 0));
        jButton_add_property.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_add_property.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_property.setText("Add");
        jButton_add_property.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_add_property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add_property.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_propertyActionPerformed(evt);
            }
        });

        jButton_edit_property.setBackground(new java.awt.Color(0, 153, 255));
        jButton_edit_property.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_edit_property.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit_property.setText("Edit");
        jButton_edit_property.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_edit_property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_edit_property.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_edit_propertyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Square Feet:");

        jTextField_Square_feet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_Square_feet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Square_feetActionPerformed(evt);
            }
        });

        jTextField_owner_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_owner_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_owner_idActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Owner Id:");

        jTextField_Price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PriceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Price (USD):");

        jButton1_Search_Property.setBackground(new java.awt.Color(51, 51, 51));
        jButton1_Search_Property.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1_Search_Property.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_Search_Property.setText("Search");
        jButton1_Search_Property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_Search_Property.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Search_PropertyActionPerformed(evt);
            }
        });

        jComboBox1_type.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Description/Comment:");

        jSpinner_Bedrooms.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinner_Bathrooms.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Bathrooms:");

        jSpinner_Age.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Age of The House:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("*0 mean brand new ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Bedrooms:");

        jTextArea_Dscription.setColumns(20);
        jTextArea_Dscription.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jTextArea_Dscription.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Dscription);

        jCheckBox_Balconey.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox_Balconey.setText("Balconey");

        jCheckBox_pool.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox_pool.setText("Pool");
        jCheckBox_pool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_poolActionPerformed(evt);
            }
        });

        jCheckBox_Backyard.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox_Backyard.setText("Backyard");
        jCheckBox_Backyard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_BackyardActionPerformed(evt);
            }
        });

        jCheckBox_Garage.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCheckBox_Garage.setText("Garage");
        jCheckBox_Garage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_GarageActionPerformed(evt);
            }
        });

        jButton_remove_property1.setBackground(new java.awt.Color(0, 0, 153));
        jButton_remove_property1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_remove_property1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove_property1.setText("Show Property");
        jButton_remove_property1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton_remove_property1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_remove_property1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_remove_property1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1_Search_Property, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField_Square_feet))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField_Price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jTextField_owner_id, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner_Bathrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner_Bedrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner_Age)))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_pool, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_Balconey, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox_Garage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_Backyard)))))
                    .addComponent(jLabel10))
                .addGap(105, 105, 105))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton_add_property, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jButton_edit_property, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_remove_property, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton_remove_property1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_Tittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jButton1_Search_Property, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                                    .addComponent(jTextField_id))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(jSpinner_Bedrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(jComboBox1_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_Square_feet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField_owner_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel10)
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jSpinner_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Balconey)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinner_Bathrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox_pool)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox_Backyard)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_Garage)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add_property, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_edit_property, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_remove_property, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_remove_property1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_remove_propertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_remove_propertyActionPerformed

        // deleting the selected property from the system
        try {
            int id = Integer.valueOf(jTextField_id.getText());

            P_PROPERTY property = new P_PROPERTY();

            if (jTextField_id.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter the Property Id", "Empty Id", 2);
            } else {
                if (!jTextField_id.getText().trim().equals("")) {// if the type name is not empty
                    // show a confirmation message before deleting the type
                    int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You Want to Delete this Property", "Delete Property", JOptionPane.YES_NO_OPTION);

                    if (yes_or_no == JOptionPane.YES_OPTION) {
                        if (property.removeProperty(id)) {
                            JOptionPane.showMessageDialog(null, "Property Data Deleted", "Deleted Property", 1);
                            
                            //clear all fields values after deleting the property
                            jTextField_id.setText("");
                            jTextArea_Address.setText(property.getAddress());
                            jTextArea_Dscription.setText("");
                            jTextField_Price.setText("");
                            jTextField_Square_feet.setText("");
                            jTextField_owner_id.setText("");
                            
                            jSpinner_Bedrooms.setValue(0);
                            jSpinner_Bathrooms.setValue(0);
                            jSpinner_Age.setValue(0);
                            
                            jCheckBox_Balconey.setSelected(false);
                            jCheckBox_Backyard.setSelected(false);
                            jCheckBox_pool.setSelected(false);
                            jCheckBox_Garage.setSelected(false);
                            
                            
                            
                        } else {
                            JOptionPane.showMessageDialog(null, "Operation failed", "Deleted Property", 2);
                        }
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "ERROR ", "Error", 0);

        }
    }//GEN-LAST:event_jButton_remove_propertyActionPerformed

    private void jButton_add_propertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_propertyActionPerformed

        //add a new property to the system 
        // get the property data from text field
        try {
            // we need to populate the jcombobox with the tyoe name 
            //and get the value (the value is integer associated with the string)

            int type = map.get(jComboBox1_type.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_owner_id.getText());
            int square_feet = Integer.valueOf(jTextField_Square_feet.getText());
            int bedrooms = Integer.valueOf(jSpinner_Bedrooms.getValue().toString());
            int bathroom = Integer.valueOf(jSpinner_Bathrooms.getValue().toString());
            int age = Integer.valueOf(jSpinner_Age.getValue().toString());

            boolean haveBalcony = false;
            boolean havePool = false;
            boolean haveBackyard = false;
            boolean haveGarage = false;

            //check if the property hacva a balcony pool backyard and garage 
            if (jCheckBox_Balconey.isSelected()) {
                haveBalcony = true;
            }
            if (jCheckBox_pool.isSelected()) {
                havePool = true;
            }
            if (jCheckBox_Backyard.isSelected()) {
                haveBackyard = true;
            }
            if (jCheckBox_Garage.isSelected()) {
                haveGarage = true;
            }

            String price = jTextField_Price.getText();
            String address = jTextArea_Address.getText();
            String description = jTextArea_Dscription.getText();

            P_PROPERTY property = new P_PROPERTY(0, type, square_feet, ownerId, price, address, bedrooms, bathroom, age, haveBalcony, havePool, haveBackyard, haveGarage, description);

            if (new P_PROPERTY().addProperty(property)) {

                JOptionPane.showMessageDialog(null, "New Property Added to the System", "Add Property", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Property Not Added to the System", "Add Property", 2);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "Enter a Valid Owner id and  Square Feet Value", "Invalid ID", 2);
        }


    }//GEN-LAST:event_jButton_add_propertyActionPerformed

    private void jButton_edit_propertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_edit_propertyActionPerformed
       
        //edit the selected Property
        try {
             int id = Integer.valueOf(jTextField_id.getText());
            int type = map.get(jComboBox1_type.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_owner_id.getText());
            int square_feet = Integer.valueOf(jTextField_Square_feet.getText());
            int bedrooms = Integer.valueOf(jSpinner_Bedrooms.getValue().toString());
            int bathroom = Integer.valueOf(jSpinner_Bathrooms.getValue().toString());
            int age = Integer.valueOf(jSpinner_Age.getValue().toString());

            boolean haveBalcony = false;
            boolean havePool = false;
            boolean haveBackyard = false;
            boolean haveGarage = false;

            //check if the property hacva a balcony pool backyard and garage 
            if (jCheckBox_Balconey.isSelected()) {
                haveBalcony = true;
            }
            if (jCheckBox_pool.isSelected()) {
                havePool = true;
            }
            if (jCheckBox_Backyard.isSelected()) {
                haveBackyard = true;
            }
            if (jCheckBox_Garage.isSelected()) {
                haveGarage = true;
            }

            String price = jTextField_Price.getText();
            String address = jTextArea_Address.getText();
            String description = jTextArea_Dscription.getText();

            P_PROPERTY property = new P_PROPERTY(id, type, square_feet, ownerId, price, address, bedrooms, bathroom, age, haveBalcony, havePool, haveBackyard, haveGarage, description);

            if (new P_PROPERTY().ediProperty(property)) {

                JOptionPane.showMessageDialog(null, "Property Data Updated", "Edit Property", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Property Data Not Updated", "Edit Property", 2);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + "Enter a Valid Property ID", "Invalid ID", 2);
        }

    }//GEN-LAST:event_jButton_edit_propertyActionPerformed

    private void jTextField_Square_feetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Square_feetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Square_feetActionPerformed

    private void jTextField_owner_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_owner_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_owner_idActionPerformed

    private void jTextField_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PriceActionPerformed

    private void jCheckBox_poolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_poolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_poolActionPerformed

    private void jCheckBox_BackyardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_BackyardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_BackyardActionPerformed

    private void jCheckBox_GarageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_GarageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_GarageActionPerformed

    private void jButton_remove_property1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_remove_property1ActionPerformed
     /// Show the table data int he jtable ad all propertues
     SHOW_PROPERTY_WINDOW showPropertyform = new SHOW_PROPERTY_WINDOW();
        showPropertyform.setVisible(true);
        showPropertyform.pack();
        showPropertyform.setLocationRelativeTo(null);
        showPropertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
     
        
        
    }//GEN-LAST:event_jButton_remove_property1ActionPerformed

    private void jButton1_Search_PropertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Search_PropertyActionPerformed
        try {
            // Retrieve and validate the property ID
            String idText = jTextField_id.getText();
            if (idText.isEmpty()) {
                throw new IllegalArgumentException("Property ID cannot be empty.");
            }

            int propertyId = Integer.valueOf(idText);
            P_PROPERTY property = new P_PROPERTY().findProperty(propertyId);

            // Check if the property was found
            if (property != null) {
                // Populate the UI fields with property data
                jTextArea_Address.setText(property.getAddress());
                jTextArea_Dscription.setText(property.getDescription());
                jTextField_Price.setText(property.getPrice());
                jTextField_Square_feet.setText(String.valueOf(property.getSize()));
                jTextField_owner_id.setText(String.valueOf(property.getOwnerId()));

                // Display the property type in the combobox
                for (Object type : map.keySet()) {
                    if (map.get(type).equals(property.getType())) {
                        jComboBox1_type.setSelectedItem(type);
                        break; // Exit loop once the type is found
                    }
                }

                // Set spinner values
                jSpinner_Bedrooms.setValue(property.getBedrooms());
                jSpinner_Bathrooms.setValue(property.getBathrooms());
                jSpinner_Age.setValue(property.getAge());

                // Set checkboxes based on property features
                jCheckBox_Balconey.setSelected(property.isBalcone());
                jCheckBox_Backyard.setSelected(property.isBackyard());
                jCheckBox_pool.setSelected(property.isPool());
                jCheckBox_Garage.setSelected(property.isGarage());
            } else {
                // Show message if property not found
                JOptionPane.showMessageDialog(null, "Property Not Found", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Property ID. Please enter a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + " - ERROR", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1_Search_PropertyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROPERTY_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Search_Property;
    private javax.swing.JButton jButton_add_property;
    private javax.swing.JButton jButton_edit_property;
    private javax.swing.JButton jButton_remove_property;
    private javax.swing.JButton jButton_remove_property1;
    private javax.swing.JCheckBox jCheckBox_Backyard;
    private javax.swing.JCheckBox jCheckBox_Balconey;
    private javax.swing.JCheckBox jCheckBox_Garage;
    private javax.swing.JCheckBox jCheckBox_pool;
    private javax.swing.JComboBox<String> jComboBox1_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Tittle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_Age;
    private javax.swing.JSpinner jSpinner_Bathrooms;
    private javax.swing.JSpinner jSpinner_Bedrooms;
    private javax.swing.JTextArea jTextArea_Address;
    private javax.swing.JTextArea jTextArea_Dscription;
    private javax.swing.JTextField jTextField_Price;
    private javax.swing.JTextField jTextField_Square_feet;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_owner_id;
    // End of variables declaration//GEN-END:variables
}
